version: '3.9'
services:
  node:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    networks:
      - user-net
    restart: always
  postgres:
    build: ./database/
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks:
      - user-net
    restart: always
networks:
  user-net:
    driver: bridge
