// // const { v4: uuid } = require('uuid');
// import { v4 as uuid } from 'uuid';

// /**
//  * Class represent a columns to a board
//  * @constructor
//  */
// export default class Column {
//   /**
//    * Columns data
//    * @param {String} id - columns id (generated by uuid)
//    * @param {String} title - columns title
//    * @param {Number} order - columns order number
//    */

//   id: string;

//   title: string;

//   order: number;

//   constructor({ id = uuid(), title = 'Title', order = 0 } = {}) {
//     this.id = id;
//     this.title = title;
//     this.order = order;
//   }
// }
